---
title: "GEE Modeling"
author: "Luke W. Johnston"
date: "`r Sys.Date()`"
output: 
    rmarkdown::html_vignette:
        toc: true
vignette: >
  %\VignetteIndexEntry{GEE Modeling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Set up and load dataset

```{r setup, message = TRUE, collapse=TRUE}
## Setup
devtools::load_all()
knitr::opts_chunk$set(collapse = TRUE, fig.width = 7, fig.height = 7)
library(dplyr)
library(tidyr)

## Variable prep
covar_nowaist <- covariates[which(!grepl("Waist", covariates))]
covar_withtag <- c(covariates, "TAG")

## Data prep
gee_results_unadj <- gee_results %>%
    dplyr::filter(model == "Unadjusted")

gee_results_adj <- gee_results %>%
    dplyr::filter(model == "Adjusted")

gee_data <- prep_gee_data(project_data)

## Functions
table_gee_sample <- function(data, caption = NULL) {
    data %>%
        select(Yterms, Xterms, sample.total) %>%
        group_by(Yterms) %>%
        summarise(MinSample = min(sample.total),
                  MaxSample = max(sample.total)) %>% 
        knitr::kable(caption = caption)
}

table_gee_int <- function(data, caption = NULL) {
    data %>% 
        filter(p.value <= 0.05) %>% 
        select(Yterms, Xterms, estimate, matches("value"), unit, model, sample.total) %>% 
        knitr::kable()
}
```

# Unadjusted GEE model

```{r tab_gee_results_unadj_sample}
gee_results_unadj %>% 
    table_gee_sample("Working sample size for unadjusted models")
```

```{r fig_gee_results_unadj}
gee_results_unadj %>% 
    plot_gee_main()
```

# Adjusted (as per final model)

```{r tab_gee_results_adj_sample}
gee_results_adj %>% 
    table_gee_sample('Working sample size for adjusted with TAG and others')
```

```{r fig_gee_results_adj}
gee_results_adj %>% 
    plot_gee_main()
```

# Adjusted with TAG

```{r gee_results_tag, cache=TRUE}
gee_results_tag <- bind_rows(
    analyze_gee(gee_data, outcomes, ne_pct, covar_withtag, 'mol%', mod = "with TAG"),
    analyze_gee(gee_data, outcomes, ne_conc, covar_withtag, 'nmol/mL', mod = "with TAG")
    ) %>% 
    tidy_gee_results()
```

```{r tab_gee_results_adj_tag_sample}
gee_results_tag %>% 
    table_gee_sample('Working sample size for adjusted with TAG and others')
```

```{r fig_gee_results_adj_tag}
gee_results_tag %>% 
    plot_gee_main()
```

# Adjusted without waist

```{r gee_results_nowaist, cache=TRUE}
gee_results_nowaist <- bind_rows(
    analyze_gee(gee_data, outcomes, ne_pct, covar_nowaist, 'mol%', mod = "No WC"),
    analyze_gee(gee_data, outcomes, ne_conc, covar_nowaist, 'nmol/mL', mod = "No WC")
    ) %>% 
    tidy_gee_results()
```

```{r tab_gee_results_adj_nowaist_sample}
gee_results_nowaist %>% 
    table_gee_sample('Working sample size for full adjusted without waist.')
```

```{r fig_gee_results_adj_nowaist}
gee_results_nowaist %>% 
    plot_gee_main()
```

# Interactions with time

```{r gee_results_int_time, cache=TRUE}
gee_results_unadj_int_time <- bind_rows(
    analyze_gee(
        gee_data,
        outcomes,
        ne_pct,
        "YearsFromBaseline",
        'mol%',
        mod = "Int with time",
        intvar = "YearsFromBaseline"
        ), 
    analyze_gee(
        gee_data,
        outcomes,
        ne_conc,
        "YearsFromBaseline",
        'nmol/mL',
        mod = "Int with time",
        intvar = "YearsFromBaseline")
    ) %>% 
    tidy_gee_results()

gee_results_adj_int_time <- bind_rows(
    analyze_gee(
        gee_data,
        outcomes,
        ne_pct,
        covariates,
        'mol%',
        mod = "Int with time",
        intvar = "YearsFromBaseline"
        ), 
    analyze_gee(
        gee_data,
        outcomes,
        ne_conc,
        covariates,
        'nmol/mL',
        mod = "Int with time",
        intvar = "YearsFromBaseline")
    ) %>% 
    tidy_gee_results()
```

```{r tab_gee_int_time}
gee_results_unadj_int_time %>% 
    table_gee_int("Interactions with time in unadjusted models.")
gee_results_adj_int_time %>% 
    table_gee_int("Interactions with time in fully adjusted models.")
```

# Interactions with sex 

```{r gee_results_int_sex}
gee_results_unadj_int_sex <- bind_rows(
    analyze_gee(
        gee_data,
        outcomes,
        ne_pct,
        c("YearsFromBaseline", "Sex"),
        'mol%',
        mod = "Int with sex",
        intvar = "Sex"
        ), 
    analyze_gee(
        gee_data,
        outcomes,
        ne_conc,
        c("YearsFromBaseline", "Sex"),
        'nmol/mL',
        mod = "Int with sex",
        intvar = "Sex")
    ) %>% 
    tidy_gee_results()

gee_results_adj_int_sex <- bind_rows(
    analyze_gee(
        gee_data,
        outcomes,
        ne_pct,
        covariates,
        'mol%',
        mod = "Int with sex",
        intvar = "Sex"
        ), 
    analyze_gee(
        gee_data,
        outcomes,
        ne_conc,
        covariates,
        'nmol/mL',
        mod = "Int with sex",
        intvar = "Sex")
    ) %>% 
    tidy_gee_results()
```

```{r tab_gee_int_sex}
gee_results_unadj_int_sex %>% 
    table_gee_int("Interactions with sex in unadjusted models.")

gee_results_adj_int_sex %>% 
    table_gee_int("Interactions with sex in fully adjusted models.")
```

# Interactions with ethnicity

```{r gee_results_int_ethn}
gee_results_unadj_int_ethn <- bind_rows(
    analyze_gee(
        gee_data,
        outcomes,
        ne_pct,
        c("YearsFromBaseline", "BiEthnicity"),
        'mol%',
        mod = "Int with ethnicity",
        intvar = "BiEthnicity"
        ), 
    analyze_gee(
        gee_data,
        outcomes,
        ne_conc,
        c("YearsFromBaseline", "BiEthnicity"),
        'nmol/mL',
        mod = "Int with ethnicity",
        intvar = "BiEthnicity")
    ) %>% 
    tidy_gee_results()

gee_results_adj_int_ethn <- bind_rows(
    analyze_gee(
        gee_data,
        outcomes,
        ne_pct,
        covariates,
        'mol%',
        mod = "Int with ethnicity",
        intvar = "BiEthnicity"
        ), 
    analyze_gee(
        gee_data,
        outcomes,
        ne_conc,
        covariates,
        'nmol/mL',
        mod = "Int with ethnicity",
        intvar = "BiEthnicity")
    ) %>% 
    tidy_gee_results()
```

```{r tab_gee_int_ethn}
gee_results_unadj_int_ethn %>% 
    table_gee_int("Interactions with ethnicity in unadjusted models.")

gee_results_adj_int_ethn %>% 
    table_gee_int("Interactions with ethnicity in fully adjusted models.")
```

# Sensitivity analysis by sex and ethnicity

## By sex

```{r strat_by_sex, cache=TRUE}
covar_nosex <- covariates[which(!grepl("Sex", covariates))]

females_only <- gee_data %>% 
    filter(Sex == "Female")
males_only <- gee_data %>% 
    filter(Sex == "Male")

gee_results_bysex <- bind_rows(
    analyze_gee(females_only, outcomes, ne_pct, covar_nosex, 'mol%', mod = "Female only"),
    analyze_gee(females_only, outcomes, ne_conc, covar_nosex, 'nmol/mL', mod = "Female only"),
    analyze_gee(males_only, outcomes, ne_pct, covar_nosex, 'mol%', mod = "Male only"),
    analyze_gee(males_only, outcomes, ne_conc, covar_nosex, 'nmol/mL', mod = "Male only")
    ) %>% 
    tidy_gee_results()
```

```{r tab_strat_by_sex}
gee_results_bysex %>% 
    filter(model == "Female only") %>% 
    table_gee_sample("Working sample size for models by female")

gee_results_bysex %>% 
    filter(model == "Male only") %>% 
    table_gee_sample("Working sample size for models by male")
```

```{r fig_strat_female, fig.cap="Female only"}
gee_results_bysex %>% 
    filter(model == "Female only") %>% 
    plot_gee_main()
```

```{r fig_strat_male, fig.cap="Male only"}
gee_results_bysex %>% 
    filter(model == "Male only") %>% 
    plot_gee_main()
```

## By ethnicity

```{r strat_by_ethn, cache=TRUE}
covar_noethn <- covariates[which(!grepl("BiEthnicity", covariates))]

european_only <- gee_data %>% 
    filter(BiEthnicity == "European")
noneuropean_only <- gee_data %>% 
    filter(BiEthnicity == "Non-European")

gee_results_byethn <- bind_rows(
    analyze_gee(european_only, outcomes, ne_pct, covar_noethn, 'mol%', mod = "European only"),
    analyze_gee(european_only, outcomes, ne_conc, covar_noethn, 'nmol/mL', mod = "European only"),
    analyze_gee(noneuropean_only, outcomes, ne_pct, covar_noethn, 'mol%', mod = "Non-European only"),
    analyze_gee(noneuropean_only, outcomes, ne_conc, covar_noethn, 'nmol/mL', mod = "Non-European only")
    ) %>% 
    tidy_gee_results()
```

```{r tab_strat_by_ethn}
gee_results_byethn %>% 
    filter(model == "European only") %>% 
    table_gee_sample("Working sample size for models by European")

gee_results_byethn %>% 
    filter(model == "Non-European only") %>% 
    table_gee_sample("Working sample size for models by Non-European")
```

```{r fig_strat_european, fig.cap="European only"}
gee_results_byethn %>% 
    filter(model == "European only") %>% 
    plot_gee_main()
```

```{r fig_strat_noneuropean, fig.cap="Non-European only"}
gee_results_byethn %>% 
    filter(model == "Non-European only") %>% 
    plot_gee_main()
```

# Covariates as time-independent

```{r covars_time_indep, cache=TRUE}
covars_as_time_indep <- gee_data %>% 
    mutate_at(vars(Waist, ALT, MET), funs(ifelse(VN == 0, ., NA))) %>% 
    fill(Waist, ALT, MET)

gee_results_covars_time_indep <- bind_rows(
    analyze_gee(covars_as_time_indep, outcomes[1:2], ne_pct, covariates, 'mol%', mod = "Covars time indep"),
    analyze_gee(covars_as_time_indep, outcomes[1:2], ne_conc, covariates, 'nmol/mL', mod = "Covars time indep"),
    analyze_gee(covars_as_time_indep, outcomes[3:4], ne_pct, covariates, 'mol%', mod = "Covars time indep"),
    analyze_gee(covars_as_time_indep, outcomes[3:4], ne_conc, covariates, 'nmol/mL', mod = "Covars time indep")
    ) %>% 
    tidy_gee_results()
```

```{r tab_covars_time_indep}
gee_results_covars_time_indep %>% 
    table_gee_sample("Working sample size for models with covariates as time independent")
```

```{r fig_covars_time_indep}
gee_results_covars_time_indep %>% 
    plot_gee_main()
```
