---
title: "GEE models"
author: "Luke W. Johnston"
output: 
    rmarkdown::html_vignette:
        toc: true
---

# Set up and load dataset

```{r setup, message = TRUE, collapse=TRUE}
knitr::opts_knit$set(root.dir = '../')
knitr::opts_chunk$set(collapse = TRUE)
```

```{r}
source('.Rprofile')
suppressMessages(run_setup())
ds <- load_data()
ds %>% 
    select(VN, TAG) %>% 
    na.omit() %>% 
    group_by(VN) %>% 
    summarize(n = n())
```

# Prep and wrangle data into GEE form

```{r geeData}
gee_df <- get_gee_data(ds)

outcomes <- c('linvHOMA', 'lISI', 'lIGIIR', 'lISSI2')
outcomes_is <- c('linvHOMA', 'lISI')
outcomes_bcf <- c('lIGIIR', 'lISSI2')
ne_pct <- grep('^pct_ne', names(gee_df), value = TRUE)
ne_conc <- c('TotalNE', grep('^ne\\d\\d', names(gee_df), value = TRUE))
covariates0 <- c('VN')
covariates_is <- c('VN', 'Waist', 'Sex', 'Ethnicity', 'BaseAge', 'ALT')
covariates_bcf <- c('VN', 'Waist', 'Sex', 'Ethnicity', 'BaseAge', 'ALT', 
                    'MET', 'AlcoholPerWk')
covariates_is_tag <- c('VN', 'Waist', 'Sex', 'Ethnicity', 'BaseAge', 'ALT', 'BaseTAG')
covariates_bcf_tag <- c('VN', 'Waist', 'Sex', 'Ethnicity', 'BaseAge', 
                        'ALT', 'MET', 'AlcoholPerWk', 'BaseTAG')
```

# Unadjusted GEE model

```{r geeResults_Unadj}
gee_results0 <- dplyr::bind_rows(
    analyze_gee(gee_df, outcomes, ne_pct, covariates0, 'mol%', adj.p = TRUE),
    analyze_gee(gee_df, outcomes, ne_conc, covariates0, 'nmol/mL', adj.p = TRUE)
    ) %>% 
    tidy_gee_results()
gee_results0 %>% 
    filter(p.value < 0.1) %>% 
    select(Yterms, Xterms, unit, estimate, p.value) %>% 
    mutate_each(funs(round(., 2)), estimate, p.value) %>% 
    pander('Unadjusted')
```

# Adjusted with or without TAG for IS

```{r geeResults_IS}
gee_results_is <- bind_rows(
    analyze_gee(gee_df, outcomes_is, ne_pct, covariates_is, 'mol%', adj.p = TRUE),
    analyze_gee(gee_df, outcomes_is, ne_conc, covariates_is, 'nmol/mL', adj.p = TRUE),
    analyze_gee(gee_df, outcomes_is, ne_pct, covariates_is_tag, 'mol%', adj.p = TRUE),
    analyze_gee(gee_df, outcomes_is, ne_conc, covariates_is_tag, 'nmol/mL', adj.p = TRUE)
    ) %>% 
    tidy_gee_results()
gee_results_is %>%
    filter(p.value < 0.1) %>% 
    select(Yterms, Xterms, unit, estimate, p.value) %>% 
    mutate_each(funs(round(., 2)), estimate, p.value) %>% 
    pander('Without or with TAG for IS')
gee_results_is %>% 
    select(Yterms, Xterms, sample.size) %>% 
    group_by(Yterms) %>% 
    summarise(MinSample = min(sample.size),
              MaxSample = max(sample.size)) %>% 
    pander('Sample size for IS')
```

# Adjusted with or without TAG for BCF

```{r geeResults_BCF}
gee_results_bcf <- bind_rows(
    analyze_gee(gee_df, outcomes_bcf, ne_pct, covariates_bcf, 'mol%', adj.p = TRUE),
    analyze_gee(gee_df, outcomes_bcf, ne_conc, covariates_bcf, 'nmol/mL', adj.p = TRUE),
    analyze_gee(gee_df, outcomes_bcf, ne_pct, covariates_bcf_tag, 'mol% (w/ tag)', adj.p = TRUE),
    analyze_gee(gee_df, outcomes_bcf, ne_conc, covariates_bcf_tag, 'nmol/mL (w/ tag)', adj.p = TRUE)
    ) %>% 
    tidy_gee_results()
gee_results_bcf %>% 
    filter(p.value < 0.05) %>% 
    select(Yterms, Xterms, unit, estimate, p.value) %>% 
    mutate_each(funs(round(., 2)), estimate, p.value) %>% 
    pander('Without or with TAG for BCF')
gee_results_bcf %>% 
    select(Yterms, Xterms, sample.size) %>% 
    group_by(Yterms) %>% 
    summarise(MinSample = min(sample.size),
              MaxSample = max(sample.size)) %>% 
    pander('Sample size for BCF')
```

# Interaction for IS

```{r geeResults_IS_int}
gee_results_is_int <- bind_rows(
    analyze_gee(gee_df, outcomes_is, ne_pct, covariates_is, 'mol%', adj.p = TRUE, int = TRUE),
    analyze_gee(gee_df, outcomes_is, ne_conc, covariates_is, 'nmol/mL', adj.p = TRUE, int = TRUE),
    analyze_gee(gee_df, outcomes_is, ne_pct, covariates_is_tag, 'mol% (w/ tag)', adj.p = TRUE, int = TRUE),
    analyze_gee(gee_df, outcomes_is, ne_conc, covariates_is_tag, 'nmol/mL (w/ tag)', adj.p = TRUE, int = TRUE)
    ) %>% 
    tidy_gee_results()
gee_results_is_int %>%
    select(p.value) %>% 
    plot()
gee_results_is_int %>%
    .$p.value %>% 
    min()
```

```{r geeResults_IS_int_sex}
gee_results_is_int_sex <- bind_rows(
    analyze_gee(gee_df, outcomes_is, ne_pct, covariates_is, 'mol%', adj.p = TRUE, int = TRUE, intvar = 'Sex'),
    analyze_gee(gee_df, outcomes_is, ne_conc, covariates_is, 'nmol/mL', adj.p = TRUE, int = TRUE, intvar = 'Sex'),
    analyze_gee(gee_df, outcomes_is, ne_pct, covariates_is_tag, 'mol% (w/ tag)', adj.p = TRUE, int = TRUE, intvar = 'Sex'),
    analyze_gee(gee_df, outcomes_is, ne_conc, covariates_is_tag, 'nmol/mL (w/ tag)', adj.p = TRUE, int = TRUE, intvar = 'Sex')
    ) %>% 
    tidy_gee_results()
gee_results_is_int_sex %>%
    select(p.value) %>% 
    plot()
gee_results_is_int_sex %>%
    filter(p.value < 0.05) %>% 
    select(Yterms, Xterms, term, estimate, conf.low, conf.high, unit) %>% 
    pander('Interactions between male and female for IS.')
```

```{r geeResults_IS_int_ethn}
gee_results_is_int_ethn <- bind_rows(
    analyze_gee(gee_df, outcomes_is, ne_pct, covariates_is, 'mol%', 
                adj.p = TRUE, int = TRUE, intvar = 'Ethnicity'),
    analyze_gee(gee_df, outcomes_is, ne_conc, covariates_is, 'nmol/mL', 
                adj.p = TRUE, int = TRUE, intvar = 'Ethnicity'),
    analyze_gee(gee_df, outcomes_is, ne_pct, covariates_is_tag, 'mol% (w/ tag)', 
                adj.p = TRUE, int = TRUE, intvar = 'Ethnicity'),
    analyze_gee(gee_df, outcomes_is, ne_conc, covariates_is_tag, 'nmol/mL (w/ tag)', 
                adj.p = TRUE, int = TRUE, intvar = 'Ethnicity')
    ) %>% 
    tidy_gee_results()
gee_results_is_int_ethn %>%
    select(p.value) %>% 
    plot()
```

# Interaction for BCF

```{r geeResults_BCF_int}
gee_results_bcf_int <- bind_rows(
    analyze_gee(gee_df, outcomes_bcf, ne_pct, covariates_bcf, 'mol%', adj.p = TRUE, int = TRUE),
    analyze_gee(gee_df, outcomes_bcf, ne_conc, covariates_bcf, 'nmol/mL', adj.p = TRUE, int = TRUE),
    analyze_gee(gee_df, outcomes_bcf, ne_pct, covariates_bcf_tag, 'mol% (w/ tag)', adj.p = TRUE, int = TRUE),
    analyze_gee(gee_df, outcomes_bcf, ne_conc, covariates_bcf_tag, 'nmol/mL (w/ tag)', adj.p = TRUE, int = TRUE)
    ) %>% 
    tidy_gee_results()
gee_results_bcf_int %>% 
    select(p.value) %>% 
    plot()
gee_results_bcf_int %>%
    .$p.value %>% 
    min()
```

```{r geeResults_BCF_int_sex}
gee_results_bcf_int_sex <- bind_rows(
    analyze_gee(gee_df, outcomes_bcf, ne_pct, covariates_bcf, 'mol%', 
                adj.p = TRUE, int = TRUE, intvar = 'Sex'),
    analyze_gee(gee_df, outcomes_bcf, ne_conc, covariates_bcf, 'nmol/mL', 
                adj.p = TRUE, int = TRUE, intvar = 'Sex'),
    analyze_gee(gee_df, outcomes_bcf, ne_pct, covariates_bcf_tag, 'mol% (w/ tag)', 
                adj.p = TRUE, int = TRUE, intvar = 'Sex'),
    analyze_gee(gee_df, outcomes_bcf, ne_conc, covariates_bcf_tag, 'nmol/mL (w/ tag)', 
                adj.p = TRUE, int = TRUE, intvar = 'Sex')
    ) %>% 
    tidy_gee_results()
gee_results_bcf_int_sex %>% 
    select(p.value) %>%
    plot()
gee_results_bcf_int_sex %>%
    filter(p.value < 0.05) %>% 
    select(Yterms, Xterms, term, estimate, conf.low, conf.high, unit) %>% 
    pander('Interactions between male and female for BCF.')
```

```{r geeResults_BCF_int_ethn}
gee_results_bcf_int_ethn <- bind_rows(
    analyze_gee(gee_df, outcomes_bcf, ne_pct, covariates_bcf, 'mol%', 
                adj.p = TRUE, int = TRUE, intvar = 'Ethnicity'),
    analyze_gee(gee_df, outcomes_bcf, ne_conc, covariates_bcf, 'nmol/mL', 
                adj.p = TRUE, int = TRUE, intvar = 'Ethnicity'),
    analyze_gee(gee_df, outcomes_bcf, ne_pct, covariates_bcf_tag, 'mol% (w/ tag)', 
                adj.p = TRUE, int = TRUE, intvar = 'Ethnicity'),
    analyze_gee(gee_df, outcomes_bcf, ne_conc, covariates_bcf_tag, 'nmol/mL (w/ tag)', 
                adj.p = TRUE, int = TRUE, intvar = 'Ethnicity')
    ) %>% 
    tidy_gee_results()
gee_results_bcf_int_ethn %>% 
    select(p.value) %>% 
    plot()
```
